# Generated by Django 5.2.7 on 2025-10-09 19:05

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('course_date', models.DateField()),
                ('start_time', models.TimeField(blank=True, default=None, null=True)),
                ('course_reference', models.CharField(blank=True, max_length=40, unique=True)),
                ('course_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('instructor_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=200)),
                ('telephone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address_line', models.CharField(blank=True, max_length=255, null=True)),
                ('town', models.CharField(blank=True, max_length=255, null=True)),
                ('postcode', models.CharField(blank=True, max_length=32, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('telephone', models.CharField(blank=True, max_length=64, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('add_as_training_location', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CourseType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('duration_days', models.PositiveSmallIntegerField(default=1)),
                ('default_course_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('default_instructor_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('has_exam', models.BooleanField(default=False, verbose_name='This course contains theoretical exam(s)')),
            ],
        ),
        migrations.CreateModel(
            name='BookingDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('day_code', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='training.booking')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('delegate_name', models.CharField(max_length=200)),
                ('delegate_email', models.EmailField(blank=True, max_length=254)),
                ('result', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('booking_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='training.bookingday')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='training.business'),
        ),
        migrations.AddField(
            model_name='booking',
            name='course_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='training.coursetype'),
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address_line', models.CharField(blank=True, max_length=255)),
                ('town', models.CharField(blank=True, max_length=120)),
                ('postcode', models.CharField(blank=True, max_length=12)),
                ('telephone', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('bank_sort_code', models.CharField(blank=True, max_length=16)),
                ('bank_account_number', models.CharField(blank=True, max_length=20)),
                ('name_on_account', models.CharField(blank=True, max_length=255)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='instructor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='training.instructor'),
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('must_change_password', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address_line', models.CharField(blank=True, max_length=255, null=True)),
                ('town', models.CharField(blank=True, max_length=255, null=True)),
                ('postcode', models.CharField(blank=True, max_length=32, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('telephone', models.CharField(blank=True, max_length=64, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_locations', to='training.business')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='training_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='training.traininglocation'),
        ),
    ]
