# Generated by Django 5.2.7 on 2025-10-08 08:34

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('course_duration_days', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('course_reference', models.CharField(max_length=64, unique=True)),
                ('course_date', models.DateField()),
                ('start_time', models.TimeField(default='09:30')),
                ('course_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('instructor_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('address_line', models.CharField(blank=True, max_length=255)),
                ('town', models.CharField(blank=True, max_length=120)),
                ('postcode', models.CharField(blank=True, max_length=12)),
                ('contact_name', models.CharField(blank=True, max_length=120)),
                ('telephone', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='CourseType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('duration_days', models.DecimalField(decimal_places=1, max_digits=3)),
                ('default_course_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('default_instructor_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('has_written_exam', models.BooleanField(default=False)),
                ('has_online_exam', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BookingDay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_no', models.PositiveIntegerField()),
                ('day_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='training.booking')),
            ],
            options={
                'unique_together': {('booking', 'day_no')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('signed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('delegate_name', models.CharField(max_length=255)),
                ('delegate_email', models.EmailField(blank=True, max_length=254)),
                ('result', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('booking_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='training.bookingday')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='training.business'),
        ),
        migrations.AddField(
            model_name='booking',
            name='course_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='training.coursetype'),
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address_line', models.CharField(blank=True, max_length=255)),
                ('town', models.CharField(blank=True, max_length=120)),
                ('postcode', models.CharField(blank=True, max_length=12)),
                ('telephone', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('bank_sort_code', models.CharField(blank=True, max_length=16)),
                ('bank_account_number', models.CharField(blank=True, max_length=20)),
                ('name_on_account', models.CharField(blank=True, max_length=255)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='training.instructor'),
        ),
        migrations.CreateModel(
            name='TrainingLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address_line', models.CharField(blank=True, max_length=255)),
                ('town', models.CharField(blank=True, max_length=120)),
                ('postcode', models.CharField(blank=True, max_length=12)),
                ('contact_name', models.CharField(blank=True, max_length=120)),
                ('telephone', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='training.business')),
            ],
            options={
                'unique_together': {('business', 'name')},
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='training_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='training.traininglocation'),
        ),
    ]
