# Generated by Django 5.2.7 on 2025-10-08 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='add_as_training_location',
            field=models.BooleanField(default=False),
        ),
    ]
