# Generated by Django 5.2.7 on 2025-10-09 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='notes',
            new_name='comments',
        ),
    ]
