# Generated by Django 5.2.7 on 2025-10-08 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_business_add_as_training_location'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='traininglocation',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='business',
            name='address_line',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='contact_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='business',
            name='postcode',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='telephone',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='town',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='traininglocation',
            name='address_line',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='traininglocation',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_locations', to='training.business'),
        ),
        migrations.AlterField(
            model_name='traininglocation',
            name='contact_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='traininglocation',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='traininglocation',
            name='postcode',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='traininglocation',
            name='telephone',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='traininglocation',
            name='town',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
