# Generated by Django 5.2.7 on 2025-10-10 12:07

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_rename_notes_booking_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetype',
            name='duration_days',
            field=models.DecimalField(decimal_places=1, default=Decimal('1.0'), max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.5')), django.core.validators.MaxValueValidator(Decimal('5.0'))]),
        ),
    ]
