# Generated by Django 5.2.7 on 2025-10-10 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_booking_cancel_reason_booking_cancelled_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In progress'), ('awaiting_closure', 'Awaiting instructor closure'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='scheduled', max_length=20),
        ),
    ]
