# Generated by Django 5.2.7 on 2025-10-10 16:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_alter_booking_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DelegateRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('job_title', models.CharField(max_length=100)),
                ('employee_id', models.CharField(blank=True, max_length=50)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking_day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='training.bookingday')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='training.instructor')),
            ],
        ),
    ]
