# Generated by Django 5.2.7 on 2025-10-10 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0006_delegateregister'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delegateregister',
            options={'ordering': ['-created_at']},
        ),
    ]
