# Generated by Django 5.2.7 on 2025-10-11 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0007_alter_delegateregister_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegateregister',
            name='health_status',
            field=models.CharField(choices=[('fit', "I am fit to take part in all the mental and physical aspects of today's course."), ('agreed_adjustments', 'I have a mental or physical impairment that I have discussed with the instructor already and am happy to continue with agreed alterations.'), ('will_discuss', 'I have a mental or physical impairment and will discuss this with the instructor.'), ('not_fit', 'I do not feel mentally and/or physically well enough to take part in training today and will speak with my own manager about this.')], default='fit', max_length=24),
        ),
    ]
