# Generated by Django 5.2.7 on 2025-10-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0008_delegateregister_health_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegateregister',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
