# Generated by Django 5.2.7 on 2025-10-11 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0009_delegateregister_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='course_notes',
            field=models.TextField(blank=True),
        ),
    ]
