# Generated by Django 5.2.7 on 2025-10-11 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0010_booking_course_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='course_notes',
            new_name='booking_notes',
        ),
    ]
