# Generated by Django 5.2.7 on 2025-10-11 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0011_rename_course_notes_booking_booking_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCompetency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, help_text='Optional short code (e.g. C1, ABC-01).', max_length=32)),
                ('name', models.CharField(help_text='What the delegate must be able to do (visible to instructors).', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Controls display order.')),
                ('is_active', models.BooleanField(default=True)),
                ('course_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencies', to='training.coursetype')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
                'constraints': [models.UniqueConstraint(fields=('course_type', 'name'), name='uniq_competency_name_per_course_type')],
            },
        ),
    ]
