# Generated by Django 5.2.7 on 2025-10-12 10:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0012_coursecompetency'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetencyAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('na', 'Not assessed'), ('ni', 'Needs improvement'), ('c', 'Competent'), ('e', 'Exceeded')], default='na', max_length=2)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('assessed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('assessed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='training.instructor')),
                ('course_competency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='training.coursecompetency')),
                ('register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='training.delegateregister')),
            ],
            options={
                'ordering': ['register_id', 'course_competency_id'],
                'unique_together': {('register', 'course_competency')},
            },
        ),
    ]
