# Generated by Django 5.2.7 on 2025-10-12 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0013_competencyassessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegateregister',
            name='outcome',
            field=models.CharField(choices=[('pending', 'Pending'), ('pass', 'Pass'), ('fail', 'Fail'), ('dnf', 'Did not finish')], default='pending', max_length=8),
        ),
    ]
