# Generated by Django 5.2.7 on 2025-10-12 12:52

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0014_delegateregister_outcome'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('prior_knowledge', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('post_knowledge', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('q_purpose_clear', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('q_personal_needs', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('q_exercises_useful', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('q_structure', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('q_pace', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('q_content_clear', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('q_instructor_knowledge', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('q_materials_quality', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('q_books_quality', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('q_venue_suitable', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('q_benefit_at_work', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('q_benefit_outside', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('wants_callback', models.BooleanField(default=False)),
                ('contact_name', models.CharField(blank=True, max_length=200)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feedback', to='training.coursetype')),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback', to='training.instructor')),
            ],
        ),
    ]
