# Generated by Django 5.2.7 on 2025-10-12 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0015_feedbackresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackresponse',
            name='overall_rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Delegate’s overall 1–5 rating', null=True),
        ),
    ]
