# Generated by Django 5.2.7 on 2025-10-13 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0016_feedbackresponse_overall_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingday',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
