# Generated by Django 5.2.7 on 2025-10-16 09:54

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0017_bookingday_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='closure_assess_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='closure_register_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='coursetype',
            name='duration_days',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.0'), max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('10.0'))]),
        ),
    ]
