# Generated by Django 5.2.7 on 2025-10-16 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0018_booking_closure_assess_manual_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Awaiting completion and sending'), ('sent', 'Sent'), ('viewed', 'Viewed'), ('paid', 'Paid'), ('awaiting_review', 'Awaiting instructor review'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('instructor_ref', models.CharField(blank=True, max_length=100)),
                ('account_name', models.CharField(blank=True, max_length=200)),
                ('sort_code', models.CharField(blank=True, max_length=20)),
                ('account_number', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='training.booking')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.instructor')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='training.invoice')),
            ],
        ),
    ]
