# Generated by Django 5.2.7 on 2025-10-19 15:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0019_invoice_invoiceitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetype',
            name='number_of_exams',
            field=models.PositiveIntegerField(blank=True, help_text="Required if 'This course contains theoretical exam(s)' is ticked.", null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddConstraint(
            model_name='coursetype',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('has_exam', False), ('number_of_exams__isnull', True)), models.Q(('has_exam', True), ('number_of_exams__gte', 1)), _connector='OR'), name='course_type_exam_consistency'),
        ),
    ]
