# Generated by Django 5.2.7 on 2025-10-21 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0022_exam_exam_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_code',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='Auto-generated: <CourseType.code><sequence:02d> (read-only).', max_length=40, unique=True),
        ),
    ]
