# Generated by Django 5.2.7 on 2025-10-21 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0023_alter_exam_exam_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_code',
            field=models.CharField(db_index=True, editable=False, max_length=40, unique=True),
        ),
    ]
