# Generated by Django 5.2.7 on 2025-10-21 10:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0025_alter_exam_exam_code_alter_exam_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='pass_mark_percent',
            field=models.PositiveSmallIntegerField(default=70, help_text='Passing threshold as a percentage (1–100).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
