# Generated by Django 5.2.7 on 2025-10-21 11:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0026_exam_pass_mark_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='allow_viva',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exam',
            name='viva_pass_percent',
            field=models.PositiveSmallIntegerField(blank=True, help_text='If enabled, viva threshold (must be between pass−10 and pass−1).', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='exam',
            name='pass_mark_percent',
            field=models.PositiveSmallIntegerField(default=80, help_text='Passing threshold as a percentage (1–100).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
