# Generated by Django 5.2.7 on 2025-10-21 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0028_examattempt_examattemptanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='retake_authorised',
            field=models.BooleanField(default=False),
        ),
    ]
