# Generated by Django 5.2.7 on 2025-11-01 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0029_examattempt_retake_authorised'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='retake_authorised_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
