# Generated by Django 5.2.7 on 2025-11-03 16:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0030_examattempt_retake_authorised_until'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccidentReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(max_length=255)),
                ('injured_name', models.CharField(max_length=255)),
                ('injured_address', models.TextField(blank=True, null=True)),
                ('what_happened', models.TextField()),
                ('injuries_sustained', models.TextField()),
                ('actions_carried_out', models.TextField()),
                ('actions_prevent_recurrence', models.TextField()),
                ('first_aider_name', models.CharField(max_length=255)),
                ('reporter_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
