# Generated by Django 5.2.7 on 2025-11-04 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0031_accidentreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='accidentreport',
            name='anonymized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
