# Generated by Django 5.2.7 on 2025-11-04 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0033_registeremaillog'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeremaillog',
            name='reason',
            field=models.TextField(blank=True),
        ),
    ]
