# Generated by Django 5.2.7 on 2025-11-10 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0034_registeremaillog_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogoOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(help_text='File in static/training/img/, e.g. logo_crown.png', max_length=200)),
                ('active', models.BooleanField(default=False)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('priority', models.PositiveSmallIntegerField(default=10, help_text='Lower = higher priority')),
            ],
            options={
                'ordering': ['priority', '-id'],
            },
        ),
    ]
