# Generated by Django 5.2.7 on 2025-11-11 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0035_logooverride'),
    ]

    operations = [
        migrations.AddField(
            model_name='competencyassessment',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='If true, instructors cannot unset this tick.'),
        ),
        migrations.AddField(
            model_name='competencyassessment',
            name='source_note',
            field=models.CharField(blank=True, help_text="Optional note (e.g. 'carried from DNF on 2025-03-12').", max_length=255),
        ),
    ]
