# Generated by Django 5.2.7 on 2025-11-12 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0036_competencyassessment_is_locked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delegateregister',
            name='booking_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registers', to='training.bookingday'),
        ),
    ]
