# Generated by Django 5.2.7 on 2025-11-13 11:54

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0037_alter_delegateregister_booking_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetype',
            name='certificate_duration',
            field=models.DecimalField(decimal_places=1, default=Decimal('3.0'), help_text='Certificate validity in years (e.g. 3.0 = 3 years).', max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.1')), django.core.validators.MaxValueValidator(Decimal('5.0'))]),
        ),
        migrations.AlterField(
            model_name='coursetype',
            name='duration_days',
            field=models.DecimalField(decimal_places=1, default=Decimal('1.0'), help_text='Enter the number of days the course runs over (e.g. 3.0 = 3 days).', max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.1')), django.core.validators.MaxValueValidator(Decimal('99.0'))]),
        ),
    ]
