# Generated by Django 5.2.7 on 2025-11-16 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0038_coursetype_certificate_duration_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='delegateregister',
            name='certificate_name',
            field=models.CharField(blank=True, help_text='If set, this name will be used on certificates instead of the original delegate name.', max_length=255),
        ),
        migrations.CreateModel(
            name='CertificateNameChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_name', models.CharField(max_length=255)),
                ('new_name', models.CharField(max_length=255)),
                ('reason', models.TextField()),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificate_name_changes', to=settings.AUTH_USER_MODEL)),
                ('register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_name_changes', to='training.delegateregister')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
    ]
