# Generated by Django 5.2.7 on 2025-11-16 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0039_delegateregister_certificate_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='admin_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='staff_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
