# Generated by Django 5.2.7 on 2025-11-19 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0040_invoice_admin_comment_invoice_staff_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Instructor",
            new_name="Personnel",
        ),
    ]
