# Generated by Django 5.2.7 on 2025-11-19 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0041_rename_instructor_to_personnel'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='viva_decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='viva_decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viva_decisions', to='training.personnel'),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='viva_notes',
            field=models.TextField(blank=True),
        ),
    ]
