# Generated by Django 5.2.7 on 2025-11-20 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0042_examattempt_viva_decided_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='can_login',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='personnel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
