# Generated by Django 5.2.7 on 2025-11-21 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0043_personnel_can_login_personnel_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='must_change_password',
            field=models.BooleanField(default=True),
        ),
    ]
