# Generated by Django 5.2.7 on 2025-11-21 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0044_personnel_must_change_password'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='personnel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='StaffProfile',
        ),
    ]
