# Generated by Django 5.2.7 on 2025-11-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0045_alter_personnel_user_delete_staffprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='address_line',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='bank_account_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='bank_sort_code',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='name_on_account',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='postcode',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='telephone',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='town',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
