# Generated by Django 5.2.7 on 2025-11-22 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0046_alter_personnel_address_line_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='avatar_color',
            field=models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('purple', 'Purple'), ('gold', 'Gold'), ('charcoal', 'Charcoal')], default='charcoal', max_length=20),
        ),
        migrations.AddField(
            model_name='personnel',
            name='avatar_icon',
            field=models.CharField(choices=[('initials', 'Initials'), ('person', 'Person'), ('star', 'Star'), ('graduation', 'Graduation Cap'), ('tools', 'Tools'), ('unicorn', 'Unicorn'), ('briefcase', 'Briefcase'), ('books', 'Books'), ('note', 'Note'), ('cog', 'Cog'), ('heart', 'Heart')], default='initials', max_length=30),
        ),
        migrations.AddField(
            model_name='personnel',
            name='avatar_pattern',
            field=models.CharField(choices=[('none', 'None'), ('dots', 'Dot Grid'), ('stripes', 'Diagonal Stripes'), ('gradient', 'Soft Gradient'), ('ring', 'Halo Ring'), ('solid', 'Solid')], default='solid', max_length=30),
        ),
        migrations.AddField(
            model_name='personnel',
            name='avatar_shape',
            field=models.CharField(choices=[('circle', 'Circle'), ('rounded', 'Rounded Square'), ('square', 'Square')], default='circle', max_length=20),
        ),
    ]
