# Generated by Django 5.2.7 on 2025-11-23 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0047_personnel_avatar_color_personnel_avatar_icon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='avatar_color',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='avatar_icon',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='avatar_pattern',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='avatar_shape',
        ),
        migrations.AddField(
            model_name='personnel',
            name='dyslexia_mode',
            field=models.BooleanField(default=False),
        ),
    ]
