# Generated by Django 5.2.7 on 2025-11-23 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0048_remove_personnel_avatar_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='pastel_background',
            field=models.CharField(choices=[('none', 'Default (off-white)'), ('cream', 'Cream'), ('yellow', 'Soft Yellow'), ('blue', 'Soft Blue'), ('green', 'Soft Green')], default='none', max_length=20),
        ),
    ]
