# Generated by Django 5.2.7 on 2025-11-23 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0049_personnel_pastel_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingday',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_days', to='training.personnel'),
        ),
    ]
