# Generated by Django 5.2.7 on 2025-11-23 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0050_bookingday_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingday',
            name='note',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
