# Generated by Django 5.2.7 on 2025-11-23 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0051_bookingday_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='precise_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='precise_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
