# Generated by Django 5.2.7 on 2025-11-24 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0052_booking_precise_lat_booking_precise_lng'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Meta setting',
                'verbose_name_plural': 'Meta settings',
            },
        ),
    ]
