# Generated by Django 5.2.7 on 2025-11-24 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0053_metasetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='allow_mileage_claim',
            field=models.BooleanField(default=True),
        ),
    ]
