# Generated by Django 5.2.7 on 2025-11-24 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0054_booking_allow_mileage_claim'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='mileage_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
