# Generated by Django 5.2.7 on 2025-11-25 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0055_booking_mileage_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='allow_accommodation',
            field=models.BooleanField(default=False),
        ),
    ]
