# Generated by Django 5.2.7 on 2025-11-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0056_booking_allow_accommodation'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='date_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
