# Generated by Django 5.2.7 on 2025-12-09 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0059_alter_feedbackresponse_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackresponse',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_responses', to='training.booking'),
        ),
    ]
