# Generated by Django 5.2.7 on 2025-12-09 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0060_alter_feedbackresponse_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='closure_assess_manual',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='closure_register_manual',
        ),
        migrations.AddField(
            model_name='booking',
            name='assessment_matrix_status',
            field=models.CharField(blank=True, choices=[('completed', 'Completed'), ('separate', 'Will send separately')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='course_registers_status',
            field=models.CharField(blank=True, choices=[('complete', 'Complete'), ('separate', 'Will send separately')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='date_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
