# Generated by Django 5.2.7 on 2025-12-10 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0061_remove_booking_closure_assess_manual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='last_notification_type',
            field=models.CharField(blank=True, default='system', max_length=32),
        ),
    ]
