# Generated by Django 5.2.7 on 2025-12-10 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0062_booking_last_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='admin_precise_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='admin_precise_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
