# Generated by Django 5.2.7 on 2026-02-19 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0063_booking_admin_precise_lat_booking_admin_precise_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='optional_modules',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_optional': True}, related_name='bookings_as_optional_modules', to='training.coursecompetency'),
        ),
        migrations.AddField(
            model_name='coursecompetency',
            name='is_optional',
            field=models.BooleanField(default=False),
        ),
    ]
