# Generated by Django 5.2.7 on 2026-02-21 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0064_booking_optional_modules_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('slides', 'Slides / Presentations'), ('handout', 'Handouts'), ('document', 'Documents'), ('policy', 'Policies'), ('template', 'Templates'), ('other', 'Other')], default='document', max_length=20)),
                ('url', models.URLField(help_text='OneDrive share link')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('course_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='training.coursetype')),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
    ]
