# Generated by Django 5.2.7 on 2026-02-21 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0065_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetype',
            name='onedrive_folder_link',
            field=models.URLField(blank=True, help_text='Optional OneDrive folder link for instructors'),
        ),
    ]
