# Generated by Django 5.2.7 on 2026-02-25 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0066_coursetype_onedrive_folder_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='examquestion',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
