# Generated by Django 5.2.7 on 2026-02-25 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0067_examquestion_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='question_order',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
