# Generated by Django 5.2.7 on 2026-02-26 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0068_examattempt_question_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='examquestion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='exam_questions/'),
        ),
    ]
