# Generated by Django 5.2.7 on 2026-02-26 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0069_examquestion_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examquestion',
            name='image',
        ),
        migrations.AddField(
            model_name='examquestion',
            name='image_url',
            field=models.URLField(blank=True, help_text='Optional image URL for this question', max_length=500, null=True),
        ),
    ]
