# Generated by Django 5.2.7 on 2026-03-10 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0071_traininglocation_is_active_and_booking_location_protect'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='totp_secret',
            field=models.CharField(blank=True, help_text='TOTP secret for 2FA', max_length=32, null=True),
        ),
    ]
