# Generated by Django 5.2.7 on 2026-03-14 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0076_business_dummy_fields_and_examattempt_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='avatar_icon',
            field=models.CharField(choices=[('initials', 'Initials'), ('person', 'Person'), ('person_badge', 'Person Badge'), ('teacher', 'Teacher'), ('star', 'Star'), ('graduation', 'Graduation Cap'), ('tools', 'Tools'), ('unicorn', 'Sparkles'), ('briefcase', 'Briefcase'), ('books', 'Books'), ('note', 'Note'), ('cog', 'Cog'), ('heart', 'Heart'), ('palette', 'Palette'), ('lightning', 'Lightning'), ('music', 'Music'), ('camera', 'Camera'), ('bug', 'Bug'), ('rocket', 'Rocket'), ('ambulance', 'Ambulance'), ('fire_engine', 'Fire Engine'), ('first_aid', 'First Aid Kit'), ('extinguisher', 'Fire Extinguisher'), ('firefighter', 'Firefighter'), ('paramedic', 'Ambulance Crew'), ('hospital', 'Hospital'), ('lifebuoy', 'Lifebuoy'), ('shield_medical', 'Medical Shield')], default='initials', max_length=30),
        ),
    ]
