# Generated by Django 5.2.7 on 2026-03-16 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0078_instructoravailability'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorAvailabilityPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('unavailable', 'Not available')], max_length=16)),
                ('days_of_week', models.CharField(help_text='Comma-separated day numbers: 0=Mon, 6=Sun', max_length=13)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_patterns', to='training.personnel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
