# Generated by Django 5.2.7 on 2026-03-16 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0079_instructoravailabilitypattern'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='totp_backup_codes',
            field=models.TextField(blank=True, help_text='JSON list of hashed one-time backup codes', null=True),
        ),
    ]
