# Generated by Django 5.2.7 on 2026-05-14 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0081_coursetype_optional_modules_required'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text='Telegram chat ID for sending notifications', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='personnel',
            name='telegram_username',
            field=models.CharField(blank=True, help_text='Telegram username for reference', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='TelegramNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('message_text', models.TextField(help_text='The message that was sent')),
                ('telegram_message_id', models.CharField(blank=True, help_text='Telegram message ID for reference', max_length=50, null=True)),
                ('notification_type', models.CharField(choices=[('admin_send', 'Sent by admin'), ('instructor_resend', 'Resent by instructor'), ('system', 'System notification')], default='admin_send', max_length=20)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_notifications', to='training.booking')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_notifications', to='training.personnel')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_telegram_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Telegram Notification',
                'verbose_name_plural': 'Telegram Notifications',
                'ordering': ['-sent_at'],
            },
        ),
    ]
