# Generated by Django 5.2.7 on 2026-06-12 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0082_personnel_default_dashboard_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetype',
            name='is_suspended',
            field=models.BooleanField(default=False, help_text='When suspended, this course type cannot be used for new bookings.'),
        ),
    ]
