# Generated by Django 5.2.7 on 2026-05-14 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0082_personnel_telegram_chat_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='notify_booking_changes',
            field=models.BooleanField(default=False, help_text='Notify for booking changes and cancellations'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='notify_new_bookings',
            field=models.BooleanField(default=False, help_text='Notify for new bookings'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='notify_reminders',
            field=models.BooleanField(default=False, help_text='Reminder messages 24 hours prior to booking'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='notify_service_updates',
            field=models.BooleanField(default=False, help_text='Service updates'),
        ),
    ]
