# Generated by Django 5.2.7 on 2026-05-16 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0083_personnel_notify_booking_changes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='telegram_link_token',
            field=models.CharField(blank=True, help_text='Unique token for linking Telegram account via QR code', max_length=64, null=True, unique=True),
        ),
    ]
