# Generated by Django 5.2.7 on 2026-06-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0087_sync_booking_precise_from_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='admin_what3words',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='booking',
            name='what3words',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
