# Generated by Django 5.2.7 on 2026-06-12 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0088_booking_what3words'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='admin_what3words',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='what3words',
        ),
    ]
