# Generated by Django 5.x

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0098_inbox_recipient_and_swaps"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="booking",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="training.booking",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="base_fee_override",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="When set, used instead of booking.instructor_fee for this instructor's invoice.",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="EmergencyTakeover",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "fee_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "mileage_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("is_full_takeover", models.BooleanField(default=False)),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emergency_takeovers",
                        to="training.booking",
                    ),
                ),
                (
                    "replaced_instructor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="emergency_takeovers_replaced",
                        to="training.personnel",
                    ),
                ),
                (
                    "taken_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emergency_takeovers_performed",
                        to="training.personnel",
                    ),
                ),
                (
                    "days",
                    models.ManyToManyField(
                        related_name="emergency_takeovers",
                        to="training.bookingday",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
