# Generated by Django 5.2.7 on 2026-06-23 14:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


def enable_first_aid_accident_reports(apps, schema_editor):
    CourseType = apps.get_model("training", "CourseType")
    CourseTypeOnlineExercise = apps.get_model("training", "CourseTypeOnlineExercise")
    AccidentReport = apps.get_model("training", "AccidentReport")
    Booking = apps.get_model("training", "Booking")
    BookingDay = apps.get_model("training", "BookingDay")

    enabled_type_ids = []
    for ct in CourseType.objects.filter(name__icontains="First Aid at Work"):
        ct.has_online_exercises = True
        ct.save(update_fields=["has_online_exercises"])
        CourseTypeOnlineExercise.objects.get_or_create(
            course_type_id=ct.id,
            exercise_key="accident_reports",
        )
        enabled_type_ids.append(ct.id)

    if not enabled_type_ids:
        return

    for report in AccidentReport.objects.filter(booking__isnull=True).iterator():
        day_booking_ids = list(
            BookingDay.objects.filter(
                date=report.date,
                booking__course_type_id__in=enabled_type_ids,
            )
            .values_list("booking_id", flat=True)
            .distinct()
        )
        if len(day_booking_ids) == 1:
            AccidentReport.objects.filter(pk=report.pk).update(booking_id=day_booking_ids[0])


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0101_booking_email_notifications"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursetype",
            name="has_online_exercises",
            field=models.BooleanField(
                default=False,
                verbose_name="Delegates need to submit online exercises (e.g. accident reports)",
            ),
        ),
        migrations.CreateModel(
            name="CourseTypeOnlineExercise",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "exercise_key",
                    models.CharField(
                        choices=[("accident_reports", "Accident reports")],
                        max_length=40,
                    ),
                ),
                (
                    "course_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="online_exercises",
                        to="training.coursetype",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="accidentreport",
            name="booking",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="accident_reports",
                to="training.booking",
            ),
        ),
        migrations.AddConstraint(
            model_name="coursetypeonlineexercise",
            constraint=models.UniqueConstraint(
                fields=("course_type", "exercise_key"),
                name="course_type_online_exercise_unique",
            ),
        ),
        migrations.RunPython(enable_first_aid_accident_reports, migrations.RunPython.noop),
    ]
