# Generated by Django 5.2.7 on 2026-06-23 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0102_course_online_exercises"),
    ]

    operations = [
        migrations.AddField(
            model_name="accidentreport",
            name="reported_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="accident_reports_received",
                to="training.personnel",
                verbose_name="Reported to",
            ),
        ),
    ]
